a:5:{i:0;s:106:"SQLSTATE[HY000] [2002] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.
";i:1;s:1458:"#0 C:\xampp\htdocs\magento\includes\src\__default.php(55588): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 C:\xampp\htdocs\magento\includes\src\__default.php(56068): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 C:\xampp\htdocs\magento\includes\src\__default.php(54253): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 C:\xampp\htdocs\magento\includes\src\__default.php(55316): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 C:\xampp\htdocs\magento\includes\src\__default.php(56176): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 C:\xampp\htdocs\magento\includes\src\__default.php(30253): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 C:\xampp\htdocs\magento\includes\src\__default.php(30184): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Object(Mage_Core_Model_Config_Element))
#7 C:\xampp\htdocs\magento\includes\src\Mage_Core_Model_Resource_Setup.php(141): Mage_Core_Model_Resource->getConnection('core_setup')
#8 C:\xampp\htdocs\magento\includes\src\Mage_Core_Model_Resource_Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#9 C:\xampp\htdocs\magento\includes\src\__default.php(20871): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#10 C:\xampp\htdocs\magento\includes\src\__default.php(20797): Mage_Core_Model_App->_initModules()
#11 C:\xampp\htdocs\magento\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#12 C:\xampp\htdocs\magento\index.php(87): Mage::run('', 'store')
#13 {main}";s:3:"url";s:9:"/magento/";s:11:"script_name";s:18:"/magento/index.php";s:4:"skin";s:7:"default";}